/*
 * Copyright 1999-2022 Bulain.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = config_info   */
/******************************************/
CREATE TABLE CONFIG_INFO (
  ID NUMBER(20) NOT NULL,
  DATA_ID NVARCHAR2(255) NOT NULL,
  GROUP_ID VARCHAR2(128),
  CONTENT NCLOB NOT NULL,
  MD5 VARCHAR2(32),
  GMT_CREATE DATE NOT NULL,
  GMT_MODIFIED DATE NOT NULL,
  SRC_USER NCLOB,
  SRC_IP VARCHAR2(50),
  APP_NAME NVARCHAR2(128),
  TENANT_ID VARCHAR2(128) DEFAULT '*',
  C_DESC NVARCHAR2(256),
  C_USE VARCHAR2(64),
  EFFECT VARCHAR2(64),
  TYPE VARCHAR2(64),
  C_SCHEMA NCLOB,
  ENCRYPTED_DATA_KEY NCLOB NOT NULL,
  PRIMARY KEY (ID)
) ;
CREATE UNIQUE INDEX UK_CONFIGINFO_1 ON CONFIG_INFO (DATA_ID,GROUP_ID,TENANT_ID);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = config_info_aggr   */
/******************************************/
CREATE TABLE CONFIG_INFO_AGGR (
  ID NUMBER(20) NOT NULL,
  DATA_ID NVARCHAR2(255) NOT NULL,
  GROUP_ID VARCHAR2(128) NOT NULL,
  DATUM_ID NVARCHAR2(255) NOT NULL,
  CONTENT NCLOB NOT NULL,
  GMT_MODIFIED DATE NOT NULL,
  APP_NAME NVARCHAR2(128),
  TENANT_ID VARCHAR2(128) DEFAULT '*',
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_CONFIGINFOAGGR_1 ON CONFIG_INFO_AGGR (DATA_ID,GROUP_ID,TENANT_ID,DATUM_ID);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = config_info_beta   */
/******************************************/
CREATE TABLE CONFIG_INFO_BETA (
  ID NUMBER(20) NOT NULL,
  DATA_ID NVARCHAR2(255) NOT NULL,
  GROUP_ID VARCHAR2(128) NOT NULL,
  APP_NAME NVARCHAR2(128),
  CONTENT NCLOB NOT NULL,
  BETA_IPS VARCHAR2(1024),
  MD5 VARCHAR2(32),
  GMT_CREATE DATE NOT NULL,
  GMT_MODIFIED DATE NOT NULL,
  SRC_USER NCLOB,
  SRC_IP VARCHAR2(50),
  TENANT_ID VARCHAR2(128) DEFAULT '*',
  ENCRYPTED_DATA_KEY NCLOB NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_CONFIGINFOBETA_1 ON CONFIG_INFO_BETA (DATA_ID,GROUP_ID,TENANT_ID);


/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = config_info_tag   */
/******************************************/
CREATE TABLE CONFIG_INFO_TAG (
  ID NUMBER(20) NOT NULL,
  DATA_ID NVARCHAR2(255) NOT NULL,
  GROUP_ID VARCHAR2(128) NOT NULL,
  TENANT_ID VARCHAR2(128) DEFAULT '*',
  TAG_ID VARCHAR2(128) NOT NULL,
  APP_NAME NVARCHAR2(128),
  CONTENT NCLOB NOT NULL,
  MD5 VARCHAR2(32),
  GMT_CREATE DATE NOT NULL,
  GMT_MODIFIED DATE NOT NULL,
  SRC_USER NCLOB,
  SRC_IP VARCHAR2(50),
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_CONFIGINFOTAG_1 ON CONFIG_INFO_TAG (DATA_ID,GROUP_ID,TENANT_ID,TAG_ID);


/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = config_tags_relation   */
/******************************************/
CREATE TABLE CONFIG_TAGS_RELATION (
  ID NUMBER(20) NOT NULL,
  TAG_NAME NVARCHAR2(128) NOT NULL,
  TAG_TYPE VARCHAR2(64),
  DATA_ID NVARCHAR2(255) NOT NULL,
  GROUP_ID VARCHAR2(128) NOT NULL,
  TENANT_ID VARCHAR2(128) DEFAULT '*',
  NID NUMBER(20) NOT NULL,
  PRIMARY KEY (NID)
);
CREATE UNIQUE INDEX UK_CONFIGTAGRELATION_1 ON CONFIG_TAGS_RELATION (ID,TAG_NAME,TAG_TYPE);
CREATE INDEX IDX_CONFIGTAGRELATION_1 ON CONFIG_TAGS_RELATION (TENANT_ID);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = group_capacity   */
/******************************************/
CREATE TABLE GROUP_CAPACITY (
  ID NUMBER(20) NOT NULL,
  GROUP_ID VARCHAR2(128) DEFAULT '*' NOT NULL,
  QUOTA NUMBER(10) DEFAULT 0 NOT NULL,
  USAGE NUMBER(10) DEFAULT 0 NOT NULL,
  MAX_SIZE NUMBER(10) DEFAULT 0 NOT NULL,
  MAX_AGGR_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  MAX_AGGR_SIZE NUMBER(10) DEFAULT 0 NOT NULL,
  MAX_HISTORY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  GMT_CREATE DATE NOT NULL,
  GMT_MODIFIED DATE NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_GROUPCAPACITY_1 ON GROUP_CAPACITY (GROUP_ID);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = his_config_info   */
/******************************************/
CREATE TABLE HIS_CONFIG_INFO (
  ID NUMBER(20) NOT NULL,
  NID NUMBER(20) NOT NULL,
  DATA_ID NVARCHAR2(255) NOT NULL,
  GROUP_ID VARCHAR2(128) NOT NULL,
  APP_NAME NVARCHAR2(128),
  CONTENT NCLOB NOT NULL,
  MD5 VARCHAR2(32),
  GMT_CREATE DATE NOT NULL,
  GMT_MODIFIED DATE NOT NULL,
  SRC_USER NCLOB,
  SRC_IP VARCHAR2(50),
  OP_TYPE CHAR(10),
  TENANT_ID VARCHAR2(128) DEFAULT '*',
  ENCRYPTED_DATA_KEY NCLOB NOT NULL,
  PRIMARY KEY (NID)
);
CREATE INDEX IDX_HISCONFIGINFO_1 ON HIS_CONFIG_INFO (GMT_CREATE);
CREATE INDEX IDX_HISCONFIGINFO_2 ON HIS_CONFIG_INFO (GMT_MODIFIED);
CREATE INDEX IDX_HISCONFIGINFO_3 ON HIS_CONFIG_INFO (DATA_ID);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = tenant_capacity   */
/******************************************/
CREATE TABLE TENANT_CAPACITY (
  ID NUMBER(20) NOT NULL,
  TENANT_ID VARCHAR2(128) DEFAULT '*' NOT NULL,
  QUOTA NUMBER(10) DEFAULT 0 NOT NULL,
  USAGE NUMBER(10) DEFAULT 0 NOT NULL,
  MAX_SIZE NUMBER(10) DEFAULT 0 NOT NULL,
  MAX_AGGR_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  MAX_AGGR_SIZE NUMBER(10) DEFAULT 0 NOT NULL,
  MAX_HISTORY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  GMT_CREATE DATE NOT NULL,
  GMT_MODIFIED DATE NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_TENANTCAPACITY_1 ON TENANT_CAPACITY (TENANT_ID);

CREATE TABLE TENANT_INFO (
  ID NUMBER(20) NOT NULL,
  KP VARCHAR2(128) NOT NULL,
  TENANT_ID VARCHAR2(128) DEFAULT '*',
  TENANT_NAME NVARCHAR2(128) DEFAULT '*',
  TENANT_DESC NVARCHAR2(256),
  CREATE_SOURCE VARCHAR2(32),
  GMT_CREATE NUMBER(20) NOT NULL,
  GMT_MODIFIED NUMBER(20) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_TENANTINFO_1 ON TENANT_INFO (KP,TENANT_ID);
CREATE INDEX IDX_TENANTINFO_1 ON TENANT_INFO (TENANT_ID);

CREATE TABLE USERS (
	USERNAME VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(500) NOT NULL,
	ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
	PRIMARY KEY (USERNAME)
);

CREATE TABLE ROLES (
	USERNAME VARCHAR2(50) NOT NULL,
	ROLE VARCHAR2(50) NOT NULL
);
CREATE UNIQUE INDEX UK_ROLES_1 ON ROLES (USERNAME, ROLE);

CREATE TABLE PERMISSIONS (
    ROLE VARCHAR2(50) NOT NULL,
    "RESOURCE" NVARCHAR2(255) NOT NULL,
    ACTION VARCHAR2(8) NOT NULL
);
CREATE UNIQUE INDEX UK_PERMISSIONS_1 ON PERMISSIONS(ROLE,"RESOURCE",ACTION);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

INSERT INTO ROLES (USERNAME, ROLE) VALUES ('nacos', 'ROLE_ADMIN');
